apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  selector:
    app: {{ .Values.backend.service.selector.app }}
    tier: {{ .Values.backend.service.selector.tier }}
  ports:
  - protocol: {{ .Values.backend.service.protocol }}
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}

