apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccountName }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::387738881290:role/frontend-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccountName }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::387738881290:role/backend-role
