# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: staging-
namespace: staging

resources:
- ../../base
- namespace.yaml
- hpa.yaml

patches:
- deployment-patch.yaml

commonLabels:
  cost-center: staging
