apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2048
spec:
  template:
    spec:
      containers:
      - name: app-2048
        image: 387738881290.dkr.ecr.us-east-1.amazonaws.com/app-repository:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: 0.5
          limits:
            memory: "512Mi"
            cpu: 0.5
        securityContext:
          allowPrivilegeEscalation: false
