# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: dev

resources:
- ../../base
- namespace.yaml

patches:
- deployment-patch.yaml

commonLabels:
  cost-center: dev
