apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 33443441290.dkr.ecr.us-east-1.amazonaws.com/app-repository:latest
        ports:
        - containerPort: 80
