# base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-2048-service
  labels:
    app: app-2048
    cost-center: common
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: app-2048
