frontend:
  name: 2048-frontend-deployment
  app: myapp
  tier: frontend
  replicas: 3
  image:
    repository: 387738881290.dkr.ecr.us-east-1.amazonaws.com/ubuntu
    tag: latest
  service:
    name: myapp-frontend-service
    type: LoadBalancer
    port: 80
    selector:
      app: myapp
      tier: frontend
  serviceAccountName: frontend-service-account
  securityContext:
    readOnlyRootFilesystem: true

backend:
  name: 2048-backend-deployment
  app: myapp
  tier: backend
  replicas: 3
  image:
    name: myappbackend
    repository: 387738881290.dkr.ecr.us-east-1.amazonaws.com/ubuntu
    tag: latest
  service:
    name: myapp-backend-service
    type: http
    port: 8080
    protocol: TCP
    selector:
      app: myapp
      tier: backend
  serviceAccountName: backend-service-account
  securityContext:
    readOnlyRootFilesystem: true
